### ISSUE TITLE
Subdomain blocked by CORS because no origin header is set

### ISSUE THREAD

**Issue by xengulai** [NoelDeMartin/laravel-dusk-mocking#19]
My application has a main app url and an admin panel located on a subdomain. The mocking requests work on the main app url, but as soon as I try to use it on a subdomain, I get "blocked by CORS policy" errors because no Access-Control-Allow-Credentials header is in the response. I'm using spatie/cors for CORS and I've debugged the flow. When laravel-dusk-mocking sends a request, it does not explicitly set an 'origin' header. When the spatie/cors package inspects the request, it cannot find an origin header so it assumes that cors is not allowed and does not set the header on the response.

**Comment by NoelDeMartin** [comment]
Hey, thanks for reporting the issue.

I've been looking into this and I'm not sure how to fix it. If you look [here](https://github.com/NoelDeMartin/laravel-dusk-mocking/blob/master/src/Browser.php#L93..L112), you'll see how the request is sent. It's actually being sent from the browser using javascript, if you continue digging the implementation you'll find it calls [this method](https://github.com/facebook/php-webdriver/blob/community/lib/Remote/RemoteWebDriver.php#L331..L339) from the webdriver library. This means the `Origin` header should already be set by the browser. What's more, I've been doing some tests to see what happens when I try to manually set the header and I get this error: "Attempt to set a forbidden header was denied: Origin". This is probably a security mechanism, so it's likely other browser will behave similarly.

So I'm not sure if it's possible to set the header manually. Maybe you could setup your cors configuration so that it accepts requests coming from the subdomain? Or even disable cors entirely when tests are running.

**Comment by xengulai** [comment]
Thanks for looking into it. Turning off CORS isn't an option, that's controlled by the selenium browser. I can turn off my middleware, but the browser is what is blocking the request because of the header not being present. When I get a little more time, I'll have to look into the selenium browser. Maybe there's a known bug with a work around.

**Comment by NoelDeMartin** [comment]
Well I didn't explain it correctly, sorry. Actually what I meant with disabling cors was enabling it everywhere. So I should have said "disable the domain filter" and just return `Access-Control-Allow-Origin: *` in the testing environment.

**Comment by NoelDeMartin** [comment]
@xengulai Did you manage to fix this?

**Comment by xengulai** [comment]
@NoelDeMartin , sorry, no, I did not. I ended up having to scrap the package on my admin panel and just use it for my front-end. I'll close this out.
